[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "gb2pr"
version = "0.1.0"
description = "Refactored gb2pr package"
authors = ["refactor"]
